In [49]:
import numpy as np
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
    load_robot_execution_failures
download_robot_execution_failures()
timeseries, y = load_robot_execution_failures()
import tsfresh
from tsfresh.feature_extraction import feature_calculators
from tsfresh.utilities.string_manipulation import get_config_from_string
from tempfile import TemporaryFile

In [8]:
from tsfresh import extract_features
extracted_features = extract_features(timeseries, column_id="id", column_sort="time")

Feature Extraction: 100%|██████████| 10/10 [00:11<00:00,  1.11s/it]


In [9]:
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

impute(extracted_features)
features_filtered = select_features(extracted_features, y)

/home/thiago/anaconda3/lib/python3.7/site-packages/tsfresh/utilities/dataframe_functions.py:173: RuntimeWarning: The columns ['F_x__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"max"'
 'F_x__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"mean"'
 'F_x__agg_linear_trend__attr_"intercept"__chunk_len_50__f_agg_"min"' ...
 'T_z__fft_coefficient__attr_"real"__coeff_98'
 'T_z__fft_coefficient__attr_"real"__coeff_99'
 'T_z__spkt_welch_density__coeff_8'] did not have any finite values. Filling with zeros.
  df.iloc[:, np.where(is_col_non_finite)[0]].columns.values), RuntimeWarning)


In [50]:
import pandas as pd

columns = np.array(list(features_filtered.columns.values))

features_names = [None] * int(features_filtered.shape[1]);


for i in range (columns.shape[0]):
    name = columns[i]
    c = '__';
    words = name.split(c)
    
    features_names[i] = 'X__' + str(c.join(words[1:]))


In [56]:
outfile1 = TemporaryFile()

In [57]:
np.save(outfile1, features_names)

In [60]:
_ = outfile1.seek(0)
np.load(outfile1)

array(['X__value_count__value_-1', 'X__abs_energy',
       'X__range_count__max_1__min_-1', 'X__abs_energy',
       'X__standard_deviation', 'X__variance',
       'X__fft_coefficient__attr_"abs"__coeff_1',
       'X__fft_coefficient__attr_"abs"__coeff_1', 'X__abs_energy',
       'X__standard_deviation', 'X__variance',
       'X__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"var"',
       'X__standard_deviation', 'X__variance',
       'X__ratio_value_number_to_time_series_length',
       'X__standard_deviation', 'X__variance',
       'X__fft_coefficient__attr_"abs"__coeff_1',
       'X__fft_coefficient__attr_"abs"__coeff_2',
       'X__cid_ce__normalize_True', 'X__partial_autocorrelation__lag_1',
       'X__autocorrelation__lag_1',
       'X__percentage_of_reoccurring_values_to_all_values',
       'X__fft_coefficient__attr_"abs"__coeff_4',
       'X__ratio_value_number_to_time_series_length',
       'X__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"',
       'X

In [61]:
def from_columns(columns, columns_to_ignore=None):
    """
    Creates a mapping from kind names to fc_parameters objects
    (which are itself mappings from feature calculators to settings)
    to extract only the features contained in the columns.
    To do so, for every feature name in columns this method

    1. split the column name into col, feature, params part
    2. decide which feature we are dealing with (aggregate with/without params or apply)
    3. add it to the new name_to_function dict
    4. set up the params

    :param columns: containing the feature names
    :type columns: list of str
    :param columns_to_ignore: columns which do not contain tsfresh feature names
    :type columns_to_ignore: list of str

    :return: The kind_to_fc_parameters object ready to be used in the extract_features function.
    :rtype: dict
    """

    kind_to_fc_parameters = {}

    if columns_to_ignore is None:
        columns_to_ignore = []

    for col in columns:
        if col in columns_to_ignore:
            continue

        if not isinstance(col, str):
            raise TypeError("Column name {} should be a string or unicode".format(col))

        # Split according to our separator into <col_name>, <feature_name>, <feature_params>
        parts = col.split('__')
        n_parts = len(parts)

        if n_parts == 1:
            raise ValueError("Splitting of columnname {} resulted in only one part.".format(col))

        kind = parts[0]
        feature_name = parts[1]

        if kind not in kind_to_fc_parameters:
            kind_to_fc_parameters[kind] = {}

        if not hasattr(feature_calculators, feature_name):
            raise ValueError("Unknown feature name {}".format(feature_name))

        config = get_config_from_string(parts)

        if config:
            if feature_name in kind_to_fc_parameters[kind]:
                if config not in kind_to_fc_parameters[kind][feature_name]:
                    kind_to_fc_parameters[kind][feature_name].append(config)
            else:
                kind_to_fc_parameters[kind][feature_name] = [config]
        else:
            kind_to_fc_parameters[kind][feature_name] = None

    return kind_to_fc_parameters

In [62]:
kind_to_fc_parameters = from_columns(features_names)
my_parameters = kind_to_fc_parameters['X']

In [63]:
extract_features(timeseries, column_id="id", column_sort="time", default_fc_parameters=my_parameters)

Feature Extraction: 100%|██████████| 10/10 [00:07<00:00,  1.35it/s]


variable  F_x__abs_energy  F_x__absolute_sum_of_changes  \
id                                                        
1                    14.0                           2.0   
2                    25.0                          14.0   
3                    12.0                          10.0   
4                    16.0                          17.0   
5                    17.0                          13.0   
..                    ...                           ...   
84                96833.0                         100.0   
85                 1683.0                          19.0   
86                83497.0                         127.0   
87              1405437.0                         181.0   
88                 1427.0                          11.0   

variable  F_x__agg_autocorrelation__f_agg_"mean"__maxlag_40  \
id                                                            
1                                                 -0.106351   
2                                                 -0.039098   
3                                                 -0.029815   
4                                                 -0.049773   
5                                                 -0.061467   
..                                                      ...   
84                                                -0.435813   
85                                                -0.599870   
86                                                -0.603352   
87                                                -0.455727   
88                                                -0.614351   

variable  F_x__agg_autocorrelation__f_agg_"median"__maxlag_40  \
id                                                              
1                                             -7.206633e-02     
2                                             -4.935275e-02     
3                                              1.301043e-17     
4                                             -6.417112e-02     
5                                             -5.172414e-02     
..                                                      ...     
84                                            -8.343714e-01     
85                                            -4.380362e-01     
86                                            -4.802260e-01     
87                                            -4.355676e-01     
88                                            -5.887814e-01     

variable  F_x__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"max"  \
id                                                                             
1                                                       0.0                    
2                                                       0.0                    
3                                                       1.0                    
4                                                       1.0                    
5                                                       2.0                    
..                                                      ...                    
84                                                    -25.0                    
85                                                     12.0                    
86                                                     70.0                    
87                                                    340.0                    
88                                                     -6.0                    

variable  F_x__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"  \
id                                                                              
1                                                      -0.9                     
2                                                      -0.7                     
3                                                      -0.5                     
4                                                      -0.4                     
5                                      

In [64]:
# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
print('___')
# create the PCA instance
pca = PCA(1)
# fit on data
pca.fit(A)
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)
print('___')
# transform data
B = pca.transform(A)
print(B)
print('___')


[[1 2]
 [3 4]
 [5 6]]
___
[[0.70710678 0.70710678]]
[8.]
___
[[-2.82842712]
 [ 0.        ]
 [ 2.82842712]]
___


In [65]:
outfile2 = TemporaryFile()

In [66]:
np.save(outfile2, pca)

In [67]:
_ = outfile2.seek(0)
np.load(outfile2,allow_pickle=True)

array(PCA(n_components=1), dtype=object)

In [68]:
# add data to the seed data-set
C = array([[1, 2], [3, 4], [5, 6],[7,8],[9,10]])
D = pca.transform(C)
print(D)

[[-2.82842712]
 [ 0.        ]
 [ 2.82842712]
 [ 5.65685425]
 [ 8.48528137]]
